# Generated by Django 5.1.5 on 2025-05-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_customuser_is_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='discription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='studentresponse',
            unique_together={('student', 'exam', 'question')},
        ),
    ]
