# Generated by Django 5.1.5 on 2025-05-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_studentexamsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='adjusted_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='manually_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='teacher_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
