# Generated by Django 5.1.5 on 2025-05-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customuser_address_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-date']},
        ),
    ]
